PRETRAINED: !!str hennet_pretrained.pt
ADD_NUM: !!bool true
ADD_ENG: !!bool true
ADD_SPECIAL: !!bool true
MAX_LENGTH: !!int 75
IMG_W: !!int 128
IMG_H: !!int 32
HEAD_NUM: !!int 8
USE_RES: !!bool true
SEPERABLE_FFN: !!bool true
MAKE_OBJECT_QUERY: !!bool false
ADAPTIVE_PE: !!bool false
RES_IN: !!int 64
MAX_SEQ_LENGTH: !!int 75
ENCODER_LAYER_NUM: !!int 5
EMBEDDING_DIM: !!int 1024
ATTENTIONAL_TRANSFORMER: !!bool false
FEED_FORWARD_DIM: !!int 2048
USE_CONV: !!bool true
RGB: !!bool false
BATCH_SIZE: !!int 1
MEAN: !!float 0.5
STD: !!float 0.5