name: ocr-deploy-v1
on:
  push:
    branches:
      - feature/deploy
jobs:
  install-requirements:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: pip install -r requirements.txt
      - run: cd inference_server/
      - run: flask run app.py
