name: ocr-deploy-v1
on:
  push:
    branches:
      - feature/deploy
jobs:
  install-requirements:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: pip install -r requirements.txt
  build-image:
    needs: [install-requirements]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to DockerHub
        uses: docker/setup-buildx-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build And Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/docker-memo:lastest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
